name: 4 - Terraform CD (Apply)

on: 
  push:
    branches:
        - main

permissions:
    id-token: write
    contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
    terraform-apply:
        name: 'Terraform Apply'
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./environments/dev
        steps:
            - name: Checkout du code
              uses: actions/checkout@v4

            - name: Installation de terraform
              uses: hashicorp/setup-terraform@v3

            - name: Connexion à Azure (OIDC)
              uses: azure/login@v2
              with:
               client-id: ${{ secrets.AZURE_CLIENT_ID }}
               tenant-id: ${{ secrets.AZURE_TENANT_ID }}
               subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: 🔐 Création des clés SSH (Publique ET Privée)
              run: |
                mkdir -p ~/.ssh
                # La clé publique pour que Terraform crée la machine
                echo "${{ secrets.AZURE_SSH_PUBLIC_KEY }}" > ~/.ssh/azure_project_key.pub
                # La clé privée pour qu'Ansible puisse s'y connecter
                echo "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" > ~/.ssh/azure_project_key
                # Sécurisation obligatoire de la clé privée, sinon SSH la refuse
                chmod 600 ~/.ssh/azure_project_key

            - name: 🏗️ Terraform Init
              run: terraform init 

            - name: 🚀 Terraform Apply 
              run: terraform apply -auto-approve -input=false -var="environment=dev" -var="project_name=potforlioproj"

            - name: 🔍 Récuperer l'IP de la VM depuis Terraform 
              id: get_ip # On donne un ID à cette étape pour l'appeler plus tard
              run: |
                VM_IP=$(terraform output -raw web_server_ip)
                # On utilise la méthode officielle des Outputs de GitHub
                echo "IP=$VM_IP" >> $GITHUB_OUTPUT
                echo "L'IP récupérée est : $VM_IP"

            - name: 📝 Générer l'inventaire Ansible dynamiquement
              run: |
                echo "[webservers]" > ../../ansible/inventory.ini
                # On récupère l'IP avec la syntaxe sécurisée des Outputs (sans soulignement jaune dans VS Code !)
                echo "${{ steps.get_ip.outputs.IP }} ansible_user=adminuser ansible_ssh_private_key_file=~/.ssh/azure_project_key" >> ../../ansible/inventory.ini
                cat ../../ansible/inventory.ini

            - name: ⚙️ Exécuter le Playbook Ansible
              env:
                ANSIBLE_HOST_KEY_CHECKING: False 
              run: |
                ansible-playbook -i ../../ansible/inventory.ini ../../ansible/deploy-webapp.yml